version: '2.3'

services:
  bot:
    image: gasoid/regular-go-bot:latest
    restart: always
    environment:
      - GIST_LOGS_URL
      - TOKEN
    env_file:
      - bot.env
    logging:
      driver: syslog
